### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by asim-altayb** [createthis/linux_gpu_mining#11]
hello 
when i run ./start.sh : 
![screenshot from 2018-08-09 11-08-31](https://user-images.githubusercontent.com/26505543/43889529-b3d0c6ba-9bc4-11e8-8cb8-88942f9d815f.png)
i get that problem

**Comment by createthis** [comment]
Try an older version of ewbf, or figure out how to get a newer version of the NVIDIA driver. Looks like a version mismatch.

**Comment by asim-altayb** [comment]
thanx pro ..
